### ISSUE TITLE
[IHM] - Filter tab

### ISSUE THREAD

**Issue by dfit** [Soulk/OPL#2]
Sur les pages de listing de repo et de pulls requests un même filtre serait le bienvenu.
Le filtre devait permettre de retourner les lignes concernant la chaîne de caractère de la recherche.

La barre de recherche du listing des repos doit être la même (graphiquement) que sur la page de pullrequests. Les 2 barres de recherches existantes doivent donc être supprimés.

**Comment by decottis** [comment]
J'ai push une première version.
Bizarement ça fonctionne pas avec des chiffres ou des nombres, enfin pas toujours. Mais marche très bien sur les nom des PR et les noms des PullRequester !

Jette un oeil, ça doit être une connerie que j'ai pas vu.

**Comment by decottis** [comment]
Non c'est bon c'est reglé. Test moi ça stp Mr le scrum master.

**Comment by dfit** [comment]
Ok je valide ton filtre, tu peux me mettre le même en place dans la pages du listing des repos ?

**Comment by decottis** [comment]
Yep.

**Comment by decottis** [comment]
Done.

**Comment by dfit** [comment]
Ok je valide la mise en place du filter, merci de ta collaboration.
